CREATE DATABASE ; /*CRIA NOVO BANCO DE DADOS*/
USE ;/*USA BANCO DE DADOS SELECIONADO*/
CREATE TABLE ;/*CRIA NOVA TABELA DENTRO DO BANCO DE DADOS*/
SHOW TABLES;/*RETORNA TABELAS E VIEWS DENTRO DO BANCO DE DADOS*/
SHOW DATABASES;/*RETORNA TODOS OS BANCOS DE DADOS DO SGBD*/
SHOW CREATE TABLE ;/*RETORNA QUERY QUE CRIOU TABELA*/
DESC ;/*MOSTRA A ESTRUTURA DA TABELA*/
STATUS;/*RETORNA STATUS DE TODO O SGBD*/
DROP TABLE ;/*DELETA TABELA DO BANCO DE DADOS*/
DROP VIEW ;/*DELETA VIEWS DO BANCO DE DADOS*/
DROP PROCEDURE ;/*DELETA PROCEDURE DO BD*/
SELECT NOW;/*RETORNA DATA/HORA ATUAL*/
INNER JOIN;/* JUNTA TABELAS NA MESMA QUERY */
ALTER TABLE CHANGE;/*ALTERA O NOME DA TABELA E O TIPO*/
ALTER TABLE ADD;/*ADICIONA COLUNA NA TABELA*/
AS ; /*NOMEIA COLUNA AO RETORNAR QUERY*/
IFNULL() AS;/*RETORNA NULOS COM MSG*/ 

--DDL - DATA DEFINITION LANGUAGE -  DEFINIÇÃO DE DADOS
 CHAR E VARCHAR --CARACTERES LITERAIS
 INT E FLOAT --NUMEROS
 BLOB --OBJETOS COMO FOTO E DOCUMENTOS
 TEXT --TEXTOS EXTENSOS
 INT PRIMARY KEY --IDENTIFICADOR ÚNICO DA TABELA
 UNIQUE --SÓ PODE SER REGISTRADO UMA VEZ NO BANCO DE DADOS 1X1 A AUSENCIA DE UNIQUE TRANSFORMA O DADO EM 1XN
 FOREIGN KEY --CHAVE ESTRANGEIRA CRIADA NA TABELA 
 REFERENCES TABELA(COLUNA) --REFERENCIA TABELA E COLUNA ESTRANGEIRA
 NULL --VAZIO
 NOT NULL --NÃO VAZIO

/*SINTAXE BÁSICA DE INSERÇÃO DE DADOS NA TABELA
EXEMPLOS:*/
/*FORMA 01 – EXCLUINDO AS COLUNAS */
INSERT INTO CLIENTE VALUES(‘JOAO’,’M’,’JOAO@GMAIL.COM’,’03652544789’,'51996325889',’PADRE CACIQUE 520 - CENTRO - OSORIO-RS’);
/*FORMA 02 -COLOCANDO AS COLUNAS - MELHOR FORMA*/
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);
/*FORMA 03 - INSERTCOMPACTO - SOMENTE MYSQL*/
INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO- SP'),
('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/*EXEMPLO DE PROJEÇÃO/SELEÇÃO*/
/*SELEÇÃO = WHERE --SUBCONJUNTO DE UM CONJUNTO TOTAL DE REGISTROS DE UMA TABELA*/
/*PROJEÇÃO = SELECT --TUDO O QUE VC QUER VER NA TELA*/
SELECT NOME, SEXO, EMAIL /*PROJEÇÃO*/
FROM CLIENTE /*ORIGEM*/
WHERE SEXO = 'F'; /*SELEÇÃO*/

SELECT MAX(COLUNA) AS MAIOR_COLUNA --RETORNA O VALOR MÁXIMO DE UMA COLUNA
FROM TABELA;

SELECT MIN(COLUNA) AS MENOR_COLUNA --RETORNA O VALOR MÍNIMO DE UMA COLUNA
FROM TABELA;

SELECT AVG(COLUNA) AS MEDIA_COLUNA --RETORNA VALOR MÉDIO DE UMA COLUNA
FROM TABELA

SELECT MAX(COLUNA1) AS MAIOR_COLUNA1, --RETORNA OS VALORES MÁXIMO, MÍNIMO E MÉDIA DE UMA COLUNA
       MIN(COLUNA1) AS MENOR_COLUNA1,
       AVG(COLUNA1) AS MEDIA_COLUNA1
FROM TABELA;

SELECT MAX(COLUNA) AS MAX_COLUNA, 
       MIN(COLUNA) AS MIN_COLUNA,
	   TRUNCATE(AVG(COLUNA),2) AS MEDIA_COLUNA --TRUNCATE NECESSITA DE DOIS PARAMETROS, UM NUMERO OU COLUNA E A QUANTIDADE DE CASAS DECIMAIS DEPOIS DA VIRGULA
	   FROM TABELA;
     
/*EXEMPLOS DE ORDER BY*/
SELECT * FROM TABELA --ORDENA PELA COLUNA SOLICITADA
ORDER BY COLUNA;

SELECT * FROM TABELA --ORDENA PELO ÍNDICE DA COLUNA
ORDER BY 1;

SELECT * FROM ALUNOS --ORDENA POR MAIS DE UMA COLUNA
ORDER BY NUMERO, NOME;

SELECT NOME FROM ALUNOS --MESCLA ORDER BY COM PROJEÇÃO
ORDER BY NUMERO, NOME;

SELECT * FROM TABELA --ORDENA EM MODO ASCENDENTE
ORDER BY COLUNA ASC;

SELECT * FROM TABELA --ORDENA EM MODO DESCENDENTE
ORDER BY COLUNA DESC;
