CREATE DATABASE ; /*CREATE NEW DATABASE*/
USE ; /*USE SELECTED DATABASE*/
CREATE TABLE ; /*CREATE NEW TABLE INSIDE THE DATABASE*/
SHOW TABLES; /*CHECK THE TABLES INSIDE THE DATABASE*/
SHOW DATABASES; /*RETURNS ALL DBMS DATABASES*/
DESC ; /*RETURN TABLE STRUCTURE*/
STATUS; /*RETURN STATUS OF THE ENTIRE DBMS*/
INSERT INTO 'TABLE' VALUES(),;/*INSERT DATA INTO TABLE*/



/*DATABASE TABLE TYPING*/
CHAR and VARCHAR --LITERAL CHARACTERS
INT and FLOAT --NUMBERS
BLOB --OBJECTS SUCH AS PHOTO AND DOCUMENTS
TXT --EXTENSIVE TEXTS
PRIMARY KEY --TABLE UNIQUE IDENTIFIER
UNIQUE --DATA CAN ONLY BE REGISTERED ONCE IN THE TABLE

/*SELECTION, PROJECTION AND JOINING*/
WHERE --SELECTS THE REQUESTED RECORD BUT DOES NOT RETURN VISUALY
SELECT --SELECTS AND VISUALLY RETURNS THE REQUESTED

AND --FOR THE QUERY OUTPUT TO BE TRUE, ALL CONDITIONS MUST BE TRUE
OR --FOR THE QUERY OUTPUT TO BE TRUE, IT IS ENOUGH THAT A CONDITION OS TRUE
